dataset_params:
  data_dir: /home/ubuntu/hjy/data/FI
          # u08 - /home/ubuntu/hjy/data/FI
  class_num: 8
          # 6/7/8
  data_type: multi_class_classification
          # multi_class_classification
          # multi_label_classification
          # label_ranking
          # label_distribution

model_params:
  backbone: resnet101
          # resnet18/50/101
          # vgg16/19
  task_type: label_ranking
          # multi_class_classification
          # multi_label_classification
          # label_ranking
          # label_distribution
  pointwise_params:
    num_heads: 8
        # 4/8/16
    dim_heads: 32
        # 16/32/64
  pairwise_params:
    pairwise_dim: 32
    base_dim: 32
  listwise_params:
    base_dim: 32
  preference2rank_params:
    base_dim: 32

train_params:
  max_epochs: 9999999
  scheduler_param:
    milestones: [1000, 2000]
    gamma: 0.5
  lr: 1.5e-4
  batch_size: 48
  dataloader_workers: 32
  print_freq: 100
  save_img_freq: 1000
  update_ckpt_freq: 1000
  save_ckpt_freq: 9999999

